/**
 * Everything generated from `lib/*.hlsl`, as text: the tables under `src/lib/`
 * and OneJS's three `.cginc` files.
 *
 * Pure: it is handed the sources and returns the files, so the drift test and
 * `lib/write.mjs` (which writes them) run exactly the same code.
 */

import { check, keyOf, parseLibrary, Printer, printedName, TranslateError, type Checked, type Expr, type Fn, type Lang } from "./translate"

export interface LibFile {
    /** Under `lib/`. */
    source: string
    /** The name OneJS includes it by, in `Resources/OneJS/`. */
    cginc: string
    guard: string
    /** What the `.cginc` includes before its own text, since the source includes nothing. */
    includes: string[]
}

/** In dependency order: a file calls only what comes before it. */
export const LIB_FILES: LibFile[] = [
    { source: "sdf2d.hlsl", cginc: "SDF2D.cginc", guard: "ONEJS_SDF2D", includes: [] },
    { source: "noise2d.hlsl", cginc: "Noise2D.cginc", guard: "ONEJS_NOISE2D", includes: [] },
    { source: "common.hlsl", cginc: "SLCommon.cginc", guard: "ONEJS_SL_COMMON_INCLUDED", includes: ["SDF2D.cginc", "Noise2D.cginc"] },
]

/**
 * The web frame's colour switch, read at runtime: `sl_Opt.x`/`sl.opt.x` is 1
 * in a Linear project (`web.ts` documents the frame). A browser build does not
 * know the project's colour space when it prints a program, so the web copy of
 * a colour dependent function keeps both branches and asks.
 */
export const WEB_LINEAR: Record<"glsl" | "wgsl", string> = { glsl: "sl_Opt.x > 0.5", wgsl: "sl.opt.x > 0.5" }

/** The distance function the VM and the Unity frame dispatch through; the web calls its shapes directly. */
const SDF_DISPATCH = "sl_sdfDistance"

export interface Generated {
    /** Path under the package root to contents. */
    tables: Record<string, string>
    /** `.cginc` name to contents. */
    cginc: Record<string, string>
}

const HEADER = `// GENERATED by lib/generate.ts from lib/*.hlsl. Do not edit: change the
// .hlsl and run \`npm run lib\`. src/lib/lib.test.ts fails when this is stale.`

export function generate(read: (source: string) => string): Generated {
    const fns: Fn[] = []
    const cginc: Record<string, string> = {}
    for (const f of LIB_FILES) {
        // A Windows checkout may hand the source over with CRLF; the output is LF either way.
        const text = read(f.source).replace(/\r\n/g, "\n")
        fns.push(...parseLibrary(text, `lib/${f.source}`))
        cginc[f.cginc] = wrapCginc(f, text)
    }
    const c = check(fns)

    // One entry per signature, both colours of one together, in source order.
    const entryOf = new Map<string, number>()
    const members: number[][] = []
    fns.forEach((fn, i) => {
        const key = keyOf(fn)
        if (!entryOf.has(key)) { entryOf.set(key, members.length); members.push([]) }
        members[entryOf.get(key)!]!.push(i)
    })
    const entryDeps = members.map((list, e) => {
        const deps = [...new Set(list.flatMap((i) => c.deps[i]!.map((d) => entryOf.get(keyOf(fns[d]!))!)))].sort((a, b) => a - b)
        for (const d of deps) if (d >= e) throw new TranslateError(`${keyOf(fns[list[0]!]!)} needs ${keyOf(fns[members[d]![0]!]!)}, which comes after it`)
        return deps
    })

    const printers = { glsl: new Printer(c, "glsl"), wgsl: new Printer(c, "wgsl"), hlsl: new Printer(c, "hlsl") }
    const web = (lang: "glsl" | "wgsl", list: number[]): string => {
        const p = printers[lang]
        const first = list[0]!
        const name = printedName(c, first, lang)
        if (list.length === 1) return p.fn(first, name)
        const gamma = list.find((i) => fns[i]!.colour === "gamma")!
        const linear = list.find((i) => fns[i]!.colour === "linear")!
        return [p.fn(gamma, `${name}_gamma`), p.fn(linear, `${name}_linear`), dispatcher(c, linear, name, lang)].join("\n")
    }
    const hlsl = (list: number[]): string | { gamma: string; linear: string } => {
        const p = printers.hlsl
        if (list.length === 1) return p.fn(list[0]!, fns[list[0]!]!.name)
        const gamma = list.find((i) => fns[i]!.colour === "gamma")!
        const linear = list.find((i) => fns[i]!.colour === "linear")!
        return { gamma: p.fn(gamma, fns[gamma]!.name), linear: p.fn(linear, fns[linear]!.name) }
    }

    const functions = members.map((list, e) => {
        const fn = fns[list[0]!]!
        return `    { name: ${q(fn.name)}, params: [${fn.params.map((p) => q(p.ty)).join(", ")}], ret: ${q(fn.ret)}, ` +
            `wgsl: ${q(printedName(c, list[0]!, "wgsl"))}, deps: [${entryDeps[e]!.join(", ")}], colour: ${list.length > 1} },`
    })
    const sdf = sdfCalls(fns)
    const table = `${HEADER}

import type { LibFunction, SdfCall } from "./types"

/** Every function in the library, in dependency order. \`deps\` are indices into this list. */
export const LIB_FUNCTIONS: readonly LibFunction[] = [
${functions.join("\n")}
]

/** Shape id to the function and where its parameters come from, read from ${SDF_DISPATCH}'s switch. */
export const SDF_CALLS: readonly SdfCall[] = [
${sdf.map((s) => `    { fn: ${q(s.fn)}, args: [${s.args.map((a) => (Array.isArray(a) ? `[${a.join(", ")}]` : `{ int: ${a.int} }`)).join(", ")}] },`).join("\n")}
]
`
    const texts = (name: string, doc: string, type: string, items: string[]) => `${HEADER}

${doc}
export const ${name}: ReadonlyArray<${type}> = [
${items.join("\n")}
]
`
    const glsl = texts("LIB_GLSL", "/** GLSL ES 3.00, by `LIB_FUNCTIONS` index. */", "string", members.map((l) => `    ${tl(web("glsl", l))},`))
    const wgsl = texts("LIB_WGSL", "/** WGSL, by `LIB_FUNCTIONS` index. Overloaded names carry their signature, as `LIB_FUNCTIONS[i].wgsl` says. */", "string", members.map((l) => `    ${tl(web("wgsl", l))},`))
    const shared = texts("LIB_HLSL",
        "/** The HLSL/Metal shared subset, by `LIB_FUNCTIONS` index. A colour dependent function has a text per colour. */",
        "string | { gamma: string; linear: string }",
        members.map((l) => {
            const h = hlsl(l)
            return typeof h === "string" ? `    ${tl(h)},` : `    {\n        gamma: ${tl(h.gamma)},\n        linear: ${tl(h.linear)},\n    },`
        }))
    return {
        tables: { "src/lib/table.ts": table, "src/lib/glsl.ts": glsl, "src/lib/wgsl.ts": wgsl, "src/lib/hlsl.ts": shared },
        cginc,
    }
}

/** A function that asks the web frame's colour switch which branch to run. */
function dispatcher(c: Checked, model: number, name: string, lang: "glsl" | "wgsl"): string {
    const fn = c.fns[model]!
    const T = lang === "wgsl"
        ? { float: "f32", float2: "vec2f", float3: "vec3f", float4: "vec4f", int: "i32", bool: "bool" }
        : { float: "float", float2: "vec2", float3: "vec3", float4: "vec4", int: "int", bool: "bool" }
    const params = fn.params.map((p) => (lang === "wgsl" ? `${p.name}: ${T[p.ty]}` : `${T[p.ty]} ${p.name}`)).join(", ")
    const args = fn.params.map((p) => p.name).join(", ")
    const head = lang === "wgsl" ? `fn ${name}(${params}) -> ${T[fn.ret]} {` : `${T[fn.ret]} ${name}(${params}) {`
    return [
        head,
        `    if (${WEB_LINEAR[lang]}) {`,
        `        return ${name}_linear(${args});`,
        "    }",
        `    return ${name}_gamma(${args});`,
        "}",
    ].join("\n")
}

export type SdfArg = number[] | { int: number }

/**
 * The shape table, read from the dispatcher rather than kept beside it.
 *
 * Each case of `sl_sdfDistance`'s switch is `return sdShape(p, ...)` with the
 * arguments drawn from `a` (slots 0..3) and `b` (4, 5): a component, a swizzle,
 * a vector built from components, or an `(int)` component. That is the whole
 * vocabulary; anything else is a change to the dispatcher that the web
 * emitter, which calls shapes directly, would need to learn first.
 */
function sdfCalls(fns: Fn[]): Array<{ fn: string; args: SdfArg[] }> {
    const fn = fns.find((f) => f.name === SDF_DISPATCH)
    const fail = (msg: string): never => { throw new TranslateError(`${SDF_DISPATCH}: ${msg}`) }
    if (fn === undefined) return fail("not found")
    const sw = fn.body.length === 1 && fn.body[0]!.k === "switch" ? fn.body[0]! : fail("its body must be one switch")
    if (sw.k !== "switch") return fail("its body must be one switch")
    const slots = (e: Expr): number[] => {
        if (e.k === "member" && e.obj.k === "id" && (e.obj.name === "a" || e.obj.name === "b")) {
            const base = e.obj.name === "a" ? 0 : 4
            return [...e.field].map((ch) => base + "xyzw".indexOf(ch))
        }
        if (e.k === "call" && e.ctor === true && (e.name === "float2" || e.name === "float3" || e.name === "float4")) return e.args.flatMap(slots)
        return fail(`an argument outside the table's vocabulary, at line ${e.line}`)
    }
    const out: Array<{ fn: string; args: SdfArg[] }> = []
    for (const c of sw.cases) {
        if (c.value === "default") continue
        if (c.value !== out.length) fail(`case ${c.value} is out of order; the cases run 0, 1, 2...`)
        const ret = c.body.length === 1 && c.body[0]!.k === "return" ? c.body[0]!.e : fail(`case ${c.value} must be one return`)
        if (ret.k !== "call" || ret.fn === undefined) return fail(`case ${c.value} must return a library call`)
        const [p, ...rest] = ret.args
        if (p?.k !== "id" || p.name !== "p") fail(`case ${c.value} must pass p first`)
        out.push({
            fn: ret.name,
            args: rest.map((a) => (a.k === "cast" && a.to === "int" ? { int: single(slots(a.e)) } : slots(a))),
        })
    }
    return out

    function single(s: number[]): number {
        if (s.length !== 1) fail("an int parameter reads one component")
        return s[0]!
    }
}

function wrapCginc(f: LibFile, source: string): string {
    return [
        `// GENERATED from lib/${f.source} in onejs-sl (github.com/Singtaa/onejs-sl).`,
        "// Do not edit this copy: change the source there and run `npm run lib`,",
        "// which rewrites it. The web backends are translated from the same text.",
        `#ifndef ${f.guard}`,
        `#define ${f.guard}`,
        ...f.includes.map((i) => `#include "${i}"`),
        "",
        source.trimEnd(),
        "",
        "#endif",
        "",
    ].join("\n")
}

const q = (s: string) => JSON.stringify(s)

/** A template literal of shader text, which never holds a backtick, `${` or a backslash. */
function tl(s: string): string {
    if (/[`\\]|\$\{/.test(s)) throw new TranslateError(`shader text holds a character a template literal would change: ${s.slice(0, 60)}`)
    return `\`\n${s}\n\``
}

export type { Lang }
